import { COLORS } from "@/constants/theme";
import { Ionicons } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import { router } from "expo-router";
import { Image, Text, TouchableOpacity, View } from "react-native";

export default function LibraryCard({ library }) {
  // Format distance accurately (1 decimal place)
  const formattedDistance = library.distance_km
    ? parseFloat(library.distance_km).toFixed(1)
    : null;

  // Format the lowest available price
  const formattedPrice = library.monthly_price
    ? Math.round(parseFloat(library.monthly_price))
    : null;

  // 📌 THE FIX: Safely parse rating to check if it's actually > 0
  const ratingValue = parseFloat(library.rating);
  const hasRating = !isNaN(ratingValue) && ratingValue > 0;

  // Boolean generated by our PostgreSQL Query
  const isOpen = library.is_open;

  // Grab the first photo from the photos array (or use a fallback)
  const coverPhoto =
    library.photos && library.photos.length > 0
      ? library.photos[0]
      : "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800";

  return (
    <TouchableOpacity
      className="mx-6 mb-6 bg-white rounded-[24px] p-2 border border-borderLight "
      activeOpacity={0.9}
      onPress={() => router.push(`/(student)/library/${library.id}`)}
    >
      {/* Image Container */}
      <View className="relative">
        <Image
          source={{ uri: coverPhoto }}
          className="w-full h-48 rounded-2xl bg-surface"
        />

        {/* DYNAMIC STATUS BADGE (Open/Closed) */}
        <View
          className={`absolute top-2 left-2 px-2 py-1 rounded-full flex-row items-center  ${
            isOpen ? "bg-emerald-500" : "bg-gray-800/90"
          }`}
        >
          <View
            className={`w-2 h-2 rounded-full mr-1.5 ${isOpen ? "bg-white" : "bg-gray-400"}`}
          />
          <Text
            className={`font-m-bold text-xs uppercase tracking-widest ${isOpen ? "text-white" : "text-gray-200"}`}
          >
            {isOpen ? "Open Now" : "Closed"}
          </Text>
        </View>

        {/* Heart Icon */}
        {/* <TouchableOpacity className="absolute top-1 right-1 bg-white/90 p-2 rounded-full ">
          <Ionicons name="heart-outline" size={20} color={COLORS.textDark} />
        </TouchableOpacity> */}

        {/* Exact Distance Badge */}
        {formattedDistance ? (
          <View className="absolute bottom-2 right-2 bg-white/95 py-1 px-2 rounded-xl  border border-white">
            <Text className="text-textDark font-m-bold text-xs">
              {formattedDistance} km away
            </Text>
          </View>
        ) : null}
      </View>

      {/* Info Section */}
      <View className="pt-3 pr-3 pl-3 pb-1 mt-1">
        <Text className="text-xl font-m-bold text-textDark mb-1">
          {library.name}
        </Text>

        <View className="flex-row items-center mb-4">
          <Ionicons name="location-sharp" size={14} color={COLORS.textLight} />
          <Text className="text-textLight ml-1 text-sm font-m">
            {library.location || library.address}, {library.city}
          </Text>
        </View>

        {/* Bottom Row (Rating & Pricing) */}
        <View className="flex-row justify-between items-end border-t border-black/5 pt-2">
          {/* Rating OR "NEW" Gradient Badge */}
          <View className="flex-row items-center pb-1">
            {hasRating ? (
              <View className="bg-orange-50 px-2 py-1.5 rounded-lg flex-row items-center border border-orange-100">
                <Ionicons name="star" size={14} color="#F59E0B" />
                <Text className="font-m-bold text-orange-700 ml-1 text-sm">
                  {ratingValue.toFixed(1)}
                </Text>
              </View>
            ) : (
              <LinearGradient
                colors={[COLORS.brand, COLORS.brandAccent]}
                start={{ x: 0, y: 0 }}
                end={{ x: 1, y: 1 }}
                className="px-3 py-1.5 rounded-lg"
                style={{ borderRadius: 15 }}
              >
                <Text className="font-m-bold text-white text-[10px] uppercase tracking-widest">
                  New
                </Text>
              </LinearGradient>
            )}
          </View>

          {/* Pricing Section */}
          <View className="flex-col items-end">
            {formattedPrice ? (
              <>
                <Text className="text-[10px] font-m-bold text-textLight uppercase tracking-widest">
                  Starts At
                </Text>
                <View className="flex-row items-baseline">
                  <Text className="text-xl font-m-extra text-textDark">
                    ₹{formattedPrice}
                  </Text>
                  <Text className="text-textLight text-xs font-m-bold mb-0.5">
                    {" "}
                    / mo
                  </Text>
                </View>
              </>
            ) : (
              <Text className="text-brand text-sm font-m-bold pb-1">
                View pricing
              </Text>
            )}
          </View>
        </View>
      </View>
    </TouchableOpacity>
  );
}
